platform :ios, '9.3'

use_frameworks!

target 'LankaQRUtilSDK_Example' do
  pod 'MPQRCoreSDK'
  pod 'LankaQRUtilSDK', :path => '../'

  target 'LankaQRUtilSDK_Tests' do
    inherit! :search_paths

    
  end
end
